/// @script is_function
// === BEGIN: is_function ===
function is_function(t) {
    var fn = string_upper(string_trim(t));
    return  fn == "RND"    // your original BASIC call
         || fn == "RND1"   // internal 1-arg postfix token
         || fn == "RND2"   // internal 2-arg postfix token
         || fn == "STR$"
         || fn == "CHR$"
         || fn == "LEFT$"
         || fn == "RIGHT$"
         || fn == "MID$"
         || fn == "ABS"
         || fn == "INT"
         || fn == "EXP"
         || fn == "LOG"
         || fn == "LOG10"
         || fn == "SGN"
         || fn == "SIN"
         || fn == "COS"
         || fn == "TAN"
         || fn == "SQR"
         || fn == "ATN"
         || fn == "SPACE$"
         || fn == "UCASE$"
         || fn == "LCASE$"
         || fn == "LTRIM$"
         || fn == "RTRIM$"
         || fn == "INSTR"
         || fn == "GETMODE"
         || fn == "SCREEN"
         || fn == "POINT"
         || fn == "REPEAT$"
         || fn == "TIMER"
         || fn == "TIME$"
         || fn == "DATE$"
         || fn == "INKEY$"
         || fn == "ASC"
         || fn == "VAL"
         || fn == "MODE1_GET_CHAR"
         || fn == "MODE1_GET_COLOR"
         || fn == "MODE1_COLOR_NAME"
         || fn == "TILECHAR"
         || fn == "TILECOLOR"
         || fn == "TILEBIT"
         || fn == "TILENAME$"
		 || fn == "LEN"
         || fn == "EOF"
         || fn == "STRING$"
         || fn == "SPRITEX"
         || fn == "SPRITEY"
         || fn == "SPRITEHIT"
         || fn == "PEEK";
}
// === END: is_function ===
