10 REM NW-BASIC Web Edition
20 PRINT "======================================="
30 PRINT "  Welcome to NW-BASIC"
40 PRINT "======================================="
50 PRINT ""
60 PRINT "Getting started:"
70 PRINT "  HELP       - list all commands"
80 PRINT "  NEW        - clear the editor"
90 PRINT "  SAVE name  - save program (persists)"
100 PRINT "  DIR        - browse saved programs"
110 PRINT "  DIR IMPORT - load from your disk"
120 PRINT "  RUN        - run current program"
130 PRINT ""
140 PRINT "Try typing a program:"
150 PRINT "  10 PRINT ""Hello, World!"""
160 PRINT "  RUN"
170 PRINT ""
180 PRINT "Contact & follow:"
190 PRINT "  JohnNWFSDeveloper@gmail.com"
200 PRINT "  @JohnNWFS on X"
210 PRINT "  (NWFS = New Worlds From Scratch)"
220 PRINT ""
230 PRINT "Press ENTER to start coding!"
