10 REM NW-BASIC Web Edition
20 PRINT "======================================="
30 PRINT "  Welcome to NW-BASIC"
40 PRINT "======================================="
60 PRINT ""
70 PRINT "Getting started:"
80 PRINT "  HELP   - list all commands"
90 PRINT "  NEW    - clear the editor"
100 PRINT "  DIR    - browse saved programs"
110 PRINT "  RUN    - run current program"
120 PRINT ""
130 PRINT "Try typing a program:"
140 PRINT "  10 PRINT ""Hello, World!"""
150 PRINT "  RUN"
160 PRINT ""
170 PRINT "Contact & follow:"
180 PRINT "  JohnNWFSDeveloper@gmail.com"
190 PRINT "  @JohnNWFS on X"
200 PRINT "  (NWFS = New Worlds From Scratch)"
210 PRINT ""
220 PRINT "Press ENTER to start coding!"
