10 PRINT "INKEY ENTER SMOKE"
20 PRINT "PRESS ENTER"
30 K$ = INKEY$
40 PRINT "LEN=";LEN(K$)
50 PRINT "ASC=";ASC(K$)
60 IF ASC(K$) = 13 THEN PRINT "PASS ENTER" ELSE PRINT "FAIL ENTER"
70 PRINT "PRESS A"
80 K$ = INKEY$
90 PRINT "K$=[";K$;"]"
100 IF K$ = "A" OR K$ = "a" THEN PRINT "PASS A" ELSE PRINT "FAIL A"
110 END
