5 REM ============================================================
10 REM MODE 2 VIEW clip smoke — VIEW/VIEW OFF + PRINT/TILE/SCROLL
20 REM ============================================================
30 MODE 2, 16
40 CLSCHAR 32, WHITE, BLACK
50 PRINTAT 0, 0, "XX", RED, BLACK
60 VIEW 4, 2, 32, 20
70 PRINTAT 0, 0, "CLIP", RED, BLACK
80 PRINTAT 6, 4, "INSIDE", GREEN, BLACK
90 TILE 6, 6, 42, YELLOW, BLACK
100 PRINTAT 0, 1, "OUT", RED, BLACK
110 IF TILECHAR(0, 0) = 88 THEN PRINT "TEST: OUTSIDE_UNTOUCHED = PASS" ELSE PRINT "TEST: OUTSIDE_UNTOUCHED = FAIL"
120 IF TILECHAR(0, 1) = 32 THEN PRINT "TEST: CLIP_ROW1 = PASS" ELSE PRINT "TEST: CLIP_ROW1 = FAIL"
130 IF TILECHAR(6, 4) = 73 THEN PRINT "TEST: PRINT_INSIDE = PASS" ELSE PRINT "TEST: PRINT_INSIDE = FAIL"
140 IF TILECHAR(6, 6) = 42 THEN PRINT "TEST: TILE_INSIDE = PASS" ELSE PRINT "TEST: TILE_INSIDE = FAIL"
150 SCROLL UP, 1
160 IF TILECHAR(6, 3) = 73 THEN PRINT "TEST: SCROLL_INSIDE = PASS" ELSE PRINT "TEST: SCROLL_INSIDE = FAIL"
170 VIEW OFF
180 PRINTAT 0, 22, "VIEW OFF OK", CYAN, BLACK
190 IF TILECHAR(0, 22) = 86 THEN PRINT "TEST: VIEW_OFF_PRINT = PASS" ELSE PRINT "TEST: VIEW_OFF_PRINT = FAIL"
200 PRINT ""
210 PRINT "VIEW CLIP SMOKE COMPLETE"
220 END