10 PRINT "NAMED DATA STREAM SMOKE"
20 DATA @numbers: 1, 2, 3, 4, 5
30 DATA @names: "ALICE", "BOB", "CHARLIE"
40 READ @numbers, X, Y
50 READ @names, N$
60 PRINT "X="; X; " Y="; Y; " N$="; N$
70 RESTORE @numbers
80 READ @numbers, A
90 PRINT "AFTER RESTORE @numbers, A="; A
100 IF X=1 AND Y=2 AND N$="ALICE" AND A=1 THEN PRINT "PASS NAMED DATA STREAMS" ELSE PRINT "FAIL NAMED DATA STREAMS"
110 PAUSE
120 END
