10 REM ============================================================
20 REM NW-BASIC NOT OPERATOR TEST
30 REM Unary NOT in expressions and IF conditions
40 REM ============================================================
50 CLS
60 PRINT "NW-BASIC NOT OPERATOR TEST"
70 PRINT "============================"
80 PRINT ""
90 IF NOT 0 THEN PRINT "TEST: NOT_ZERO = PASS" ELSE PRINT "TEST: NOT_ZERO = FAIL"
100 IF NOT 1 THEN PRINT "TEST: NOT_ONE = FAIL" ELSE PRINT "TEST: NOT_ONE = PASS"
110 X = 0
120 IF NOT X THEN PRINT "TEST: NOT_VAR = PASS" ELSE PRINT "TEST: NOT_VAR = FAIL"
130 IF NOT (5 > 10) THEN PRINT "TEST: NOT_EXPR = PASS" ELSE PRINT "TEST: NOT_EXPR = FAIL"
140 IF NOT 0 AND 1 THEN PRINT "TEST: NOT_AND = PASS" ELSE PRINT "TEST: NOT_AND = FAIL"
150 PRINT ""
160 PRINT "NOT OPERATOR TEST COMPLETE"
170 END