5 REM AUTOTEST_SCREENSHOT
10 REM ============================================================
20 REM NW-BASIC COLOR PARSE TEST — Phase 7 (int64 hex)
30 REM Verifies named colors and hex prefixes via TILECOLOR readback
40 REM Output on tile grid: TEST: name = PASS or FAIL
50 REM ============================================================
60 MODE 2,16
70 CLSCHAR 32, WHITE, BLACK
80 R = 1
90 PRINTAT 0, 0, "NW-BASIC COLOR PARSE TEST (Phase 7)", YELLOW, BLACK
100 PRINTAT 0, R, "===================================", CYAN, BLACK
110 R = R + 2
120 REM --- Named colors ---
130 CHARAT 0, R, 65, RED, BLACK
140 CHARAT 1, R, 66, GREEN, BLACK
150 CHARAT 2, R, 67, BLUE, BLACK
160 IF TILENAME$(TILECOLOR(0, R)) = "RED" THEN PRINTAT 0, R + 1, "TEST: NAME_RED = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 1, "TEST: NAME_RED = FAIL", RED, BLACK
170 IF TILENAME$(TILECOLOR(1, R)) = "GREEN" THEN PRINTAT 0, R + 2, "TEST: NAME_GREEN = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 2, "TEST: NAME_GREEN = FAIL", RED, BLACK
180 IF TILENAME$(TILECOLOR(2, R)) = "BLUE" THEN PRINTAT 0, R + 3, "TEST: NAME_BLUE = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 3, "TEST: NAME_BLUE = FAIL", RED, BLACK
190 R = R + 5
200 REM --- Hex prefixes match named equivalents ---
210 CHARAT 0, R, 72, "#FF0000", BLACK
220 CHARAT 1, R, 73, RED, BLACK
230 CHARAT 2, R, 74, "&H00FF00", BLACK
240 CHARAT 3, R, 75, GREEN, BLACK
250 CHARAT 4, R, 76, "0x0000FF", BLACK
260 CHARAT 5, R, 77, BLUE, BLACK
270 IF TILECOLOR(0, R) = TILECOLOR(1, R) THEN PRINTAT 0, R + 1, "TEST: HEX_HASH_RED = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 1, "TEST: HEX_HASH_RED = FAIL", RED, BLACK
280 IF TILECOLOR(2, R) = TILECOLOR(3, R) THEN PRINTAT 0, R + 2, "TEST: HEX_BAS_H_GREEN = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 2, "TEST: HEX_BAS_H_GREEN = FAIL", RED, BLACK
290 IF TILECOLOR(4, R) = TILECOLOR(5, R) THEN PRINTAT 0, R + 3, "TEST: HEX_0X_BLUE = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 3, "TEST: HEX_0X_BLUE = FAIL", RED, BLACK
300 R = R + 5
310 REM --- Dollar hex + grey alias ---
320 CHARAT 0, R, 90, "$FFA500", BLACK
330 CHARAT 1, R, 91, ORANGE, BLACK
340 IF TILECOLOR(0, R) = TILECOLOR(1, R) THEN PRINTAT 0, R + 1, "TEST: HEX_DOLLAR_ORANGE = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 1, "TEST: HEX_DOLLAR_ORANGE = FAIL", RED, BLACK
350 CHARAT 2, R, 92, GREY, BLACK
360 CHARAT 3, R, 93, GRAY, BLACK
370 IF TILECOLOR(2, R) = TILECOLOR(3, R) THEN PRINTAT 0, R + 2, "TEST: GREY_ALIAS = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 2, "TEST: GREY_ALIAS = FAIL", RED, BLACK
380 PRINTAT 0, R + 4, "COLOR PARSE TEST COMPLETE", YELLOW, BLACK
390 END