5 REM AUTOTEST_SCREENSHOT
10 REM ============================================================
20 REM NW-BASIC COLOR STRUCT TEST — Phase 9 (named color table)
30 REM global.colors is a GML struct; TILENAME$ + expression constants
40 REM ============================================================
60 MODE 2,16
70 CLSCHAR 32, WHITE, BLACK
80 R = 1
90 PRINTAT 0, 0, "NW-BASIC COLOR STRUCT TEST (Phase 9)", YELLOW, BLACK
100 PRINTAT 0, R, "====================================", CYAN, BLACK
110 R = R + 2
120 REM --- Named colors + TILENAME$ reverse lookup ---
130 CHARAT 0, R, 65, NAVY, BLACK
140 CHARAT 1, R, 66, LIME, BLACK
150 CHARAT 2, R, 67, DKGRAY, BLACK
160 IF TILENAME$(TILECOLOR(0, R)) = "NAVY" THEN PRINTAT 0, R + 1, "TEST: NAME_NAVY = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 1, "TEST: NAME_NAVY = FAIL", RED, BLACK
170 IF TILENAME$(TILECOLOR(1, R)) = "LIME" THEN PRINTAT 0, R + 2, "TEST: NAME_LIME = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 2, "TEST: NAME_LIME = FAIL", RED, BLACK
180 IF TILENAME$(TILECOLOR(2, R)) = "DKGRAY" THEN PRINTAT 0, R + 3, "TEST: NAME_DKGRAY = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 3, "TEST: NAME_DKGRAY = FAIL", RED, BLACK
190 R = R + 5
200 REM --- Expression color constants (postfix evaluator path) ---
210 PSET 0, R, 79, ORANGE, BLACK
220 IF TILECOLOR(0, R) = ORANGE THEN PRINTAT 0, R + 1, "TEST: EXPR_ORANGE = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 1, "TEST: EXPR_ORANGE = FAIL", RED, BLACK
230 PSET 1, R, 77, MAGENTA, BLACK
240 IF TILECOLOR(1, R) = MAGENTA THEN PRINTAT 0, R + 2, "TEST: EXPR_MAGENTA = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 2, "TEST: EXPR_MAGENTA = FAIL", RED, BLACK
250 PRINTAT 0, R + 4, "COLOR STRUCT TEST COMPLETE", YELLOW, BLACK
260 END