5 REM AUTOTEST_SCREENSHOT
10 REM ============================================================
20 REM NW-BASIC EXPRESSION COLOR TEST — hex in expressions
30 REM TILECOLOR(...) = &H / $ / # literals (not just commands)
40 REM ============================================================
60 MODE 2,16
70 CLSCHAR 32, WHITE, BLACK
80 R = 2
90 PRINTAT 0, 0, "NW-BASIC EXPR COLOR TEST", YELLOW, BLACK
100 CHARAT 0, R, 72, GREEN, BLACK
110 IF TILECOLOR(0, R) = &H00FF00 THEN PRINTAT 0, R + 1, "TEST: EXPR_ANDH = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 1, "TEST: EXPR_ANDH = FAIL", RED, BLACK
120 CHARAT 1, R, 73, ORANGE, BLACK
130 IF TILECOLOR(1, R) = $FFA500 THEN PRINTAT 0, R + 2, "TEST: EXPR_DOLLAR = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 2, "TEST: EXPR_DOLLAR = FAIL", RED, BLACK
140 CHARAT 2, R, 74, RED, BLACK
150 IF TILECOLOR(2, R) = #FF0000 THEN PRINTAT 0, R + 3, "TEST: EXPR_HASH = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 3, "TEST: EXPR_HASH = FAIL", RED, BLACK
160 PRINTAT 0, R + 5, "EXPR COLOR TEST COMPLETE", YELLOW, BLACK
170 END