10 REM ============================================================
20 REM NW-BASIC FIX / CINT smoke test
30 REM FIX truncates toward zero; CINT rounds to nearest integer
40 REM ============================================================
50 CLS
60 PRINT "NW-BASIC FIX / CINT TEST"
70 PRINT "========================"
80 PRINT ""
90 IF FIX(3.7) = 3 THEN PRINT "TEST: FIX_POS = PASS" ELSE PRINT "TEST: FIX_POS = FAIL"
100 IF FIX(-3.7) = -3 THEN PRINT "TEST: FIX_NEG = PASS" ELSE PRINT "TEST: FIX_NEG = FAIL"
110 IF INT(-3.7) = -4 THEN PRINT "TEST: INT_CONTRAST = PASS" ELSE PRINT "TEST: INT_CONTRAST = FAIL"
120 IF CINT(3.4) = 3 THEN PRINT "TEST: CINT_DOWN = PASS" ELSE PRINT "TEST: CINT_DOWN = FAIL"
130 IF CINT(3.6) = 4 THEN PRINT "TEST: CINT_UP = PASS" ELSE PRINT "TEST: CINT_UP = FAIL"
140 IF CINT(2.5) = 3 THEN PRINT "TEST: CINT_HALF_POS = PASS" ELSE PRINT "TEST: CINT_HALF_POS = FAIL"
150 IF CINT(-2.5) = -3 THEN PRINT "TEST: CINT_HALF_NEG = PASS" ELSE PRINT "TEST: CINT_HALF_NEG = FAIL"
160 PRINT ""
170 PRINT "FIX / CINT TEST COMPLETE"
180 END