5 REM AUTOTEST_SCREENSHOT
10 REM ============================================================
20 REM NW-BASIC COLOR COMMAND TEST — Phase 8 (unified parser)
30 REM PSET / CLSCHAR use basic_parse_color for all prefixes
40 REM ============================================================
60 MODE 2,16
70 CLSCHAR 32, BLACK, BLACK
80 R = 2
90 PRINTAT 0, 0, "NW-BASIC COLOR COMMAND TEST (Phase 8)", YELLOW, BLACK
100 REM --- PSET hex vs named ---
110 PSET 0, R, 72, &H00FF00, BLACK
120 PSET 1, R, 73, GREEN, BLACK
130 IF TILECOLOR(0, R) = TILECOLOR(1, R) THEN PRINTAT 0, R + 1, "TEST: PSET_ANDH_GREEN = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 1, "TEST: PSET_ANDH_GREEN = FAIL", RED, BLACK
140 PSET 2, R, 74, $FFA500, BLACK
150 PSET 3, R, 75, ORANGE, BLACK
160 IF TILECOLOR(2, R) = TILECOLOR(3, R) THEN PRINTAT 0, R + 2, "TEST: PSET_DOLLAR_ORANGE = PASS", GREEN, BLACK ELSE PRINTAT 0, R + 2, "TEST: PSET_DOLLAR_ORANGE = FAIL", RED, BLACK
170 R = R + 4
180 REM --- CLSCHAR hex fill readback ---
190 CLSCHAR 46, &H0000FF, BLACK
200 IF TILENAME$(TILECOLOR(4, R)) = "BLUE" THEN PRINTAT 0, R, "TEST: CLSCHAR_ANDH_BLUE = PASS", GREEN, BLACK ELSE PRINTAT 0, R, "TEST: CLSCHAR_ANDH_BLUE = FAIL", RED, BLACK
210 CLSCHAR 32, BLACK, BLACK
220 PRINTAT 0, R + 2, "COLOR COMMAND TEST COMPLETE", YELLOW, BLACK
230 END